import { Component } from '@angular/core';
import { CardCatComponent } from '../../components/card-cat/card-cat.component';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { FooterComponent } from '../../components/footer/footer.component';
import { IPet } from '../../model/ipet';

@Component({
  selector: 'app-cat',
  standalone: true,
  imports: [CardCatComponent, NavbarComponent, FooterComponent],
  templateUrl: './cat.component.html',
  styleUrl: './cat.component.css'
})
export class CatComponent {
  gatos:IPet[] = [
    {
      id:1,
      img:'../../../assets/cat-01.jpg',
      nome:'Manu',
      genero:'Fêmea',
      idade:2,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:2,
      img:'../../../assets/cat-02.jpg',
      nome:'Bono',
      genero:'Macho',
      idade:4,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:3,
      img:'../../../assets/cat-03.jpg',
      nome:'Iron',
      genero:'Macho',
      idade:1,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:4,
      img:'../../../assets/cat-04.jpg',
      nome:'Pantera',
      genero:'Macho',
      idade:3,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:5,
      img:'../../../assets/cat-05.jpg',
      nome:'Lua',
      genero:'Fêmea',
      idade:1,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:6,
      img:'../../../assets/cat-06.jpg',
      nome:'James',
      genero:'Macho',
      idade:4,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:7,
      img:'../../../assets/cat-07.jpg',
      nome:'Berlim',
      genero:'Macho',
      idade:6,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:8,
      img:'../../../assets/cat-08.jpg',
      nome:'Cindy',
      genero:'Fêmea',
      idade:3,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:9,
      img:'../../../assets/cat-09.jpg',
      nome:'Theo',
      genero:'Macho',
      idade:1,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:10,
      img:'../../../assets/cat-10.jpg',
      nome:'Raul',
      genero:'Macho',
      idade:3,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:11,
      img:'../../../assets/cat-11.jpg',
      nome:'Bowie',
      genero:'Macho',
      idade:2,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
    {
      id:12,
      img:'../../../assets/cat-12.jpg',
      nome:'Aurora',
      genero:'Fêmea',
      idade:5,
      castrado:true,
      vermifugado:true,
      porte:'Pequeno',
      termos:'Ser maior de 21 anos, Apresentar documentação básica (cópia de RG e CPF), Cópia do comprovante de endereço, Passar pela entrevista de adoção com um responsável da VidaPet, Para adoção de gatinhos, levar caixa de transporte ou adquiri-la conosco, Para adotar cães, é indispensável levar a guia peitoral ou adquiri-la conosco.',
    },
  ]
}
